# Generated by Django 4.2 on 2023-04-11 13:56

import authlogin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='createdOn',
            field=models.DateTimeField(default=authlogin.models.currentTime),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='email',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
