# Generated by Django 4.2 on 2023-04-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0002_question_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
            ],
        ),
    ]
